---
name: App-ZofCMS-Plugin-GoogleCalculator
version: 0.0102
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: simple plugin to interface with Google calculator
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS::Plugin::Base: 0.0103
  WWW::Google::Calculator: 0.05
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::GoogleCalculator:
    file: lib/App/ZofCMS/Plugin/GoogleCalculator.pm
    version: 0.0102
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
